# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20161219_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(),
        ),
    ]
