# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20161220_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media/None/no-img', upload_to='media/'),
        ),
    ]
