# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default=None, upload_to='static/media/'),
        ),
    ]
