# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20161230_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
