# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20161230_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(upload_to='photos'),
        ),
    ]
