# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20161230_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
