# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20161230_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingred1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred10',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred6',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred7',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred8',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred9',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
