# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20161230_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingred1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred10',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred8',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingred9',
        ),
    ]
